FROM almalinux:9
#RUN cd /tmp  #cd command will not work in docker container
#RUN mkdir /app  #RUN command will not work in docker container
WORKDIR /app
RUN echo "Present directory: ${PWD}"
CMD ["sleep", "100"]